server:
  port: 80
  
spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  type-aliases-package: com.daesung.shorturl.model
  mapper-locations:
  - /mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/url?serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&autoReconnection=true
    username: url_test
    password: 4321
